use chrono::Local;
use comrak::{markdown_to_html, Options};
use std::fs;
use std::path::Path;

// ── Helpers ───────────────────────────────────────────────────────────────────

fn extract_title_from_md(content: &str) -> Option<String> {
    content
        .lines()
        .find_map(|line| line.trim().strip_prefix("# ").map(|s| s.trim().to_string()))
        .filter(|s| !s.is_empty())
}

fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

fn build_html(title: &str, body: &str, date: &str) -> String {
    const TEMPLATE: &str = r#"<!doctype html><html><head><meta charset="utf-8"><style>
@page { size: A4; margin: 22mm 18mm; }
* { box-sizing: border-box; }
body { font-family: -apple-system, "Helvetica Neue", Helvetica, Arial, sans-serif; color: #1a1a1a; font-size: 11pt; line-height: 1.55; margin: 0; }
.doc-header { border-bottom: 2px solid #1E3A5F; padding-bottom: 10px; margin-bottom: 26px; display: flex; align-items: baseline; justify-content: space-between; }
.doc-title { font-size: 21pt; font-weight: 700; letter-spacing: -0.01em; color: #111; margin: 0; }
.doc-date { font-size: 9pt; color: #6b7280; text-transform: uppercase; letter-spacing: 0.08em; white-space: nowrap; padding-left: 16px; }
h1 { font-size: 16pt; font-weight: 700; margin: 26px 0 8px; color: #111; }
h2 { font-size: 13pt; font-weight: 700; margin: 22px 0 6px; color: #1E3A5F; }
h3 { font-size: 11.5pt; font-weight: 700; margin: 18px 0 4px; color: #333; }
p { margin: 0 0 10px; }
ul, ol { margin: 0 0 12px; padding-left: 20px; }
li { margin: 0 0 4px; }
a { color: #1E3A5F; text-decoration: none; border-bottom: 1px solid #c7d2e0; }
blockquote { border-left: 3px solid #1E3A5F; margin: 12px 0; padding: 2px 0 2px 14px; color: #4b5563; }
code { font-family: "SF Mono", "JetBrains Mono", Menlo, monospace; font-size: 9.5pt; background: #f3f4f6; padding: 1px 4px; border-radius: 3px; }
pre { background: #0d1117; color: #e6edf3; padding: 12px 14px; border-radius: 6px; overflow-x: auto; font-size: 9pt; line-height: 1.45; }
pre code { background: none; padding: 0; color: inherit; }
table { border-collapse: collapse; width: 100%; margin: 12px 0; font-size: 10pt; }
th, td { border: 1px solid #e5e7eb; padding: 6px 9px; text-align: left; vertical-align: top; }
th { background: #f3f4f6; font-weight: 600; }
hr { border: none; border-top: 1px solid #e5e7eb; margin: 22px 0; }
.doc-footer { margin-top: 30px; padding-top: 8px; border-top: 1px solid #e5e7eb; font-size: 8.5pt; color: #9ca3af; }
</style></head><body>
<div class="doc-header"><h1 class="doc-title">{{TITLE}}</h1><span class="doc-date">{{DATE}}</span></div>
{{BODY}}
<div class="doc-footer">Generated by Antfarm · {{DATE}}</div>
</body></html>"#;

    TEMPLATE
        .replace("{{BODY}}", body)
        .replace("{{TITLE}}", &html_escape(title))
        .replace("{{DATE}}", date)
}

// ── Filter ────────────────────────────────────────────────────────────────────

/// True for paths matching `.../active/reports/*.md`.
pub(crate) fn is_active_report(path: &str) -> bool {
    let p = Path::new(path);
    if p.extension().and_then(|e| e.to_str()) != Some("md") {
        return false;
    }
    let Some(parent) = p.parent() else {
        return false;
    };
    let Some(grandparent) = parent.parent() else {
        return false;
    };
    parent.file_name().and_then(|n| n.to_str()) == Some("reports")
        && grandparent.file_name().and_then(|n| n.to_str()) == Some("active")
}

// ── Core render ───────────────────────────────────────────────────────────────

pub(crate) fn render_pdf_from_md(md_path: &str) -> Result<String, String> {
    // Guard: reject traversal and wrong extension.
    if md_path.contains("..") {
        return Err("path traversal not allowed".into());
    }
    let path = Path::new(md_path);
    if !path.exists() {
        return Err(format!("file not found: {md_path}"));
    }
    if path.extension().and_then(|e| e.to_str()) != Some("md") {
        return Err("path must end in .md".into());
    }

    // Read markdown; extract title.
    let content = fs::read_to_string(path).map_err(|e| e.to_string())?;
    let title = extract_title_from_md(&content).unwrap_or_else(|| {
        path.file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("Report")
            .to_string()
    });

    // Render GFM → HTML.
    let mut opts = Options::default();
    opts.extension.table = true;
    opts.extension.strikethrough = true;
    opts.extension.autolink = true;
    opts.extension.tasklist = true;
    let body_html = markdown_to_html(&content, &opts);

    let date = Local::now().format("%B %-d, %Y").to_string();
    let html = build_html(&title, &body_html, &date);

    // Write temp HTML next to the .md file.
    let html_path = path.with_extension("tmp.html");
    fs::write(&html_path, &html).map_err(|e| e.to_string())?;

    // Find a headless Chrome/Chromium browser.
    let chrome_candidates = [
        "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
        "/Applications/Chromium.app/Contents/MacOS/Chromium",
        "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge",
        "/Applications/Brave Browser.app/Contents/MacOS/Brave Browser",
    ];
    let chrome = chrome_candidates
        .iter()
        .find(|&&p| Path::new(p).exists())
        .copied()
        .ok_or_else(|| "No Chrome/Chromium found to render PDF".to_string())?;

    let pdf_path = path.with_extension("pdf");
    let html_url = format!("file://{}", html_path.to_string_lossy());

    let result = std::process::Command::new(chrome)
        .args([
            "--headless=new",
            "--disable-gpu",
            "--no-pdf-header-footer",
            "--virtual-time-budget=2000",
            &format!("--print-to-pdf={}", pdf_path.to_string_lossy()),
            &html_url,
        ])
        .output()
        .map_err(|e| e.to_string());

    // Always delete the temp HTML, even on error.
    let _ = fs::remove_file(&html_path);

    let output = result?;
    if !output.status.success() {
        return Err(format!(
            "Chrome exited with {}: {}",
            output.status,
            String::from_utf8_lossy(&output.stderr)
        ));
    }

    pdf_path
        .to_str()
        .map(|s| s.to_string())
        .ok_or_else(|| "invalid PDF path encoding".to_string())
}

// ── Tauri command ─────────────────────────────────────────────────────────────

#[tauri::command]
pub fn render_report_pdf(md_path: String) -> Result<String, String> {
    render_pdf_from_md(&md_path)
}
